DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY(
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR (250) NOT NULL
);

DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);




DROP TABLE IF EXISTS AUTOR;

CREATE TABLE AUTOR (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    nombre VARCHAR(400) NOT NULL,
    nacionalidad VARCHAR(250)  
);

DROP TABLE IF EXISTS GAME;

CREATE TABLE GAME (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    age VARCHAR(3) NOT NULL,
    category_id BIGINT DEFAULT NULL,
    author_id BIGINT DEFAULT NULL
);

ALTER TABLE GAME ADD FOREIGN KEY (category_id) REFERENCES CATEGORY(id);
ALTER TABLE GAME ADD FOREIGN KEY (author_id) REFERENCES AUTOR(id);

DROP TABLE IF EXISTS PRESTAMOS;

CREATE TABLE PRESTAMOS (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  juego_id BIGINT DEFAULT NULL,
  cliente_id BIGINT DEFAULT NULL,
  fecha_Inicio VARCHAR(250) NOT NULL,
  fecha_Fin VARCHAR(250) NOT NULL
);

ALTER TABLE PRESTAMOS ADD FOREIGN KEY (juego_id) REFERENCES GAME(id);
ALTER TABLE PRESTAMOS ADD FOREIGN KEY (cliente_id) REFERENCES CLIENTES(id);
